In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [14]:
class KNearestNeighbors:
    def __init__(self, n_neighbors=5):
        self.n_neighbors = n_neighbors
        self.x = np.array([])
        self.y = np.array([])
        
    def fit(self, x, y):
        self.x=x
        self.y=y
        
    def predict(self, p):
        d = self.dist(p,self.x)
        d1={}
        neighbors=[]
        for i in range(len(d)):
            d1[i] = d[i]
        s = [(k, d1[k]) for k in sorted(d1, key=d1.get)]
        for (k, v) in s:
            neighbors.append(k)
        #print(neighbors)
        labels = []
        for i in range(self.n_neighbors):
            labels.append(self.y[neighbors[i]])
            #print(y[neighbors[i]])
        #print(labels)
        return np.array(labels).mean().round()
        
    def dist(self, p1, p):
        d=np.array([])
        for i in range(len(p)):
            d = np.append(d,np.sqrt(((p1-p[i])**2).sum()))
        return d

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
x = iris.data
y = iris.target

In [3]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

c:\python34\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [19]:
knn = KNearestNeighbors(n_neighbors=4)
knn.fit(X_train, y_train)
y_pred = []
for i in X_test:
    y_pred.append(knn.predict(i))
#y_pred

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
cl = classification_report(y_test,np.array(y_pred))
cm = confusion_matrix(y_test,np.array(y_pred))
print(cl)
print(cm)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       1.00      0.89      0.94        19
          2       0.87      1.00      0.93        13

avg / total       0.96      0.96      0.96        45

[[13  0  0]
 [ 0 17  2]
 [ 0  0 13]]
